version: '3.8'

services:
  metrics-consumer-microservice:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile
    container_name: metrics-consumer-microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/metrics
    networks:
      - microservice-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - microservice-network
    volumes:
      - mongo-data:/data/db

networks:
  microservice-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local